version: "3" # docker compose version
services:  # 실행하려는 컨테이너 정의
  redis-server: # 컨테이너 이름
    image: 'redis' # 컨테이너에서 사용하는 이미지
  node-app: # 컨테이너 이름
    build: . # 현재 디렉토리에 있는 도커파일 사용
    ports:
      - "5000:8080" # 포트매핑(호스트포트:컨테이너 포트)